### ISSUE TITLE
itkVtkViewerCDN.js:2 Uncaught ReferenceError: __itk_viewer_version__ is not defined

### ISSUE THREAD

**Issue by Davegb** [Kitware/itk-vtk-viewer#462]
I'm getting this error when I open a HTML file with the following code:

```
<!DOCTYPE html>
<html>
  <head>
    <meta http-equiv="Content-type" content="text/html; charset=utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1">
  </head>
  <body>
    <div
      style="float: right; display: inline-block; border: 2px solid gray; margin: 20px; margin-right: 50px;"
      class="itk-vtk-viewer"
      data-url="https://data.kitware.com/api/v1/file/564a65d58d777f7522dbfb61/download/data.nrrd"
      data-viewport="450x300"
    ></div>
    <script type="text/javascript" src="https://unpkg.io/itk-vtk-viewer/dist/itkVtkViewerCDN.js"></script>
  </body>
</html>
```

The stacktrace is:

```
itkVtkViewerCDN.js:2 Uncaught ReferenceError: __itk_viewer_version__ is not defined
    at Module.921 (itkVtkViewerCDN.js:2:787079)
    at n (itkVtkViewerCDN.js:2:3192725)
    at Object.4275 (itkVtkViewerCDN.js:2:50758)
    at n (itkVtkViewerCDN.js:2:3192725)
    at itkVtkViewerCDN.js:2:3193588
    at itkVtkViewerCDN.js:2:3193597
    at itkVtkViewerCDN.js:2:216
    at itkVtkViewerCDN.js:2:220
```

**Comment by PaulHax** [comment]
Hola!  Try this for your `src` attribute:

`<script type="text/javascript" src="https://cdn.jsdelivr.net/npm/itk-vtk-viewer@11.12.4/dist/itkVtkViewer.min.js"></script>`

**Comment by Davegb** [comment]
Thank you! That worked!
